// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.0
// source: proto/client_detail.proto

package upms

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientDetailsSvc_SaveEntity_FullMethodName    = "/xyz.grpc.upms.ClientDetailsSvc/SaveEntity"
	ClientDetailsSvc_FindById_FullMethodName      = "/xyz.grpc.upms.ClientDetailsSvc/FindById"
	ClientDetailsSvc_GetByClientId_FullMethodName = "/xyz.grpc.upms.ClientDetailsSvc/GetByClientId"
)

// ClientDetailsSvcClient is the client API for ClientDetailsSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 客户端详情查询服务
type ClientDetailsSvcClient interface {
	// 保存
	SaveEntity(ctx context.Context, in *ClientDetails, opts ...grpc.CallOption) (*ClientDetails, error)
	// 根据ID查询
	FindById(ctx context.Context, in *FindByIdReq, opts ...grpc.CallOption) (*ClientDetails, error)
	// 业务方法
	// 根据客户端ID查询客户端详情信息
	GetByClientId(ctx context.Context, in *GetByClientIdReq, opts ...grpc.CallOption) (*ClientDetails, error)
}

type clientDetailsSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewClientDetailsSvcClient(cc grpc.ClientConnInterface) ClientDetailsSvcClient {
	return &clientDetailsSvcClient{cc}
}

func (c *clientDetailsSvcClient) SaveEntity(ctx context.Context, in *ClientDetails, opts ...grpc.CallOption) (*ClientDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientDetails)
	err := c.cc.Invoke(ctx, ClientDetailsSvc_SaveEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientDetailsSvcClient) FindById(ctx context.Context, in *FindByIdReq, opts ...grpc.CallOption) (*ClientDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientDetails)
	err := c.cc.Invoke(ctx, ClientDetailsSvc_FindById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientDetailsSvcClient) GetByClientId(ctx context.Context, in *GetByClientIdReq, opts ...grpc.CallOption) (*ClientDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientDetails)
	err := c.cc.Invoke(ctx, ClientDetailsSvc_GetByClientId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientDetailsSvcServer is the server API for ClientDetailsSvc service.
// All implementations must embed UnimplementedClientDetailsSvcServer
// for forward compatibility.
//
// 客户端详情查询服务
type ClientDetailsSvcServer interface {
	// 保存
	SaveEntity(context.Context, *ClientDetails) (*ClientDetails, error)
	// 根据ID查询
	FindById(context.Context, *FindByIdReq) (*ClientDetails, error)
	// 业务方法
	// 根据客户端ID查询客户端详情信息
	GetByClientId(context.Context, *GetByClientIdReq) (*ClientDetails, error)
	mustEmbedUnimplementedClientDetailsSvcServer()
}

// UnimplementedClientDetailsSvcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientDetailsSvcServer struct{}

func (UnimplementedClientDetailsSvcServer) SaveEntity(context.Context, *ClientDetails) (*ClientDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveEntity not implemented")
}
func (UnimplementedClientDetailsSvcServer) FindById(context.Context, *FindByIdReq) (*ClientDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method FindById not implemented")
}
func (UnimplementedClientDetailsSvcServer) GetByClientId(context.Context, *GetByClientIdReq) (*ClientDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByClientId not implemented")
}
func (UnimplementedClientDetailsSvcServer) mustEmbedUnimplementedClientDetailsSvcServer() {}
func (UnimplementedClientDetailsSvcServer) testEmbeddedByValue()                          {}

// UnsafeClientDetailsSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientDetailsSvcServer will
// result in compilation errors.
type UnsafeClientDetailsSvcServer interface {
	mustEmbedUnimplementedClientDetailsSvcServer()
}

func RegisterClientDetailsSvcServer(s grpc.ServiceRegistrar, srv ClientDetailsSvcServer) {
	// If the following call panics, it indicates UnimplementedClientDetailsSvcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientDetailsSvc_ServiceDesc, srv)
}

func _ClientDetailsSvc_SaveEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientDetailsSvcServer).SaveEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientDetailsSvc_SaveEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientDetailsSvcServer).SaveEntity(ctx, req.(*ClientDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientDetailsSvc_FindById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientDetailsSvcServer).FindById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientDetailsSvc_FindById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientDetailsSvcServer).FindById(ctx, req.(*FindByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientDetailsSvc_GetByClientId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByClientIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientDetailsSvcServer).GetByClientId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientDetailsSvc_GetByClientId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientDetailsSvcServer).GetByClientId(ctx, req.(*GetByClientIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientDetailsSvc_ServiceDesc is the grpc.ServiceDesc for ClientDetailsSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientDetailsSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xyz.grpc.upms.ClientDetailsSvc",
	HandlerType: (*ClientDetailsSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveEntity",
			Handler:    _ClientDetailsSvc_SaveEntity_Handler,
		},
		{
			MethodName: "FindById",
			Handler:    _ClientDetailsSvc_FindById_Handler,
		},
		{
			MethodName: "GetByClientId",
			Handler:    _ClientDetailsSvc_GetByClientId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/client_detail.proto",
}
