// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: proto/client_detail.proto

package upms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 根据客户端ID获取详情请求
type GetByClientIdReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 客户端ID
	ClientId      string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByClientIdReq) Reset() {
	*x = GetByClientIdReq{}
	mi := &file_proto_client_detail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByClientIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByClientIdReq) ProtoMessage() {}

func (x *GetByClientIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_detail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByClientIdReq.ProtoReflect.Descriptor instead.
func (*GetByClientIdReq) Descriptor() ([]byte, []int) {
	return file_proto_client_detail_proto_rawDescGZIP(), []int{0}
}

func (x *GetByClientIdReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// 客户端详情信息
type ClientDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 组织ID（租户ID）
	TenantId int64 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// 客户端ID
	ClientId string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// 客户端密钥
	ClientSecret string `protobuf:"bytes,4,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	// 客户端名称
	ClientName string `protobuf:"bytes,5,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	// 客户端有效开始时间
	ClientIdIssuedAt int64 `protobuf:"varint,6,opt,name=client_id_issued_at,json=clientIdIssuedAt,proto3" json:"client_id_issued_at,omitempty"`
	// 客户端有效结束时间
	ClientSecretExpiresAt int64 `protobuf:"varint,7,opt,name=client_secret_expires_at,json=clientSecretExpiresAt,proto3" json:"client_secret_expires_at,omitempty"`
	// 客户端认证方式
	ClientAuthenticationMethods []string `protobuf:"bytes,8,rep,name=client_authentication_methods,json=clientAuthenticationMethods,proto3" json:"client_authentication_methods,omitempty"`
	// 客户端授权方式
	AuthorizationGrantTypes []string `protobuf:"bytes,9,rep,name=authorization_grant_types,json=authorizationGrantTypes,proto3" json:"authorization_grant_types,omitempty"`
	// 客户端回调地址
	RedirectUris []string `protobuf:"bytes,10,rep,name=redirect_uris,json=redirectUris,proto3" json:"redirect_uris,omitempty"`
	// 客户端授权范围
	Scopes []string `protobuf:"bytes,11,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// 客户端配置
	ClientSettings string `protobuf:"bytes,12,opt,name=client_settings,json=clientSettings,proto3" json:"client_settings,omitempty"`
	// 客户端令牌配置
	TokenSettings string `protobuf:"bytes,13,opt,name=token_settings,json=tokenSettings,proto3" json:"token_settings,omitempty"`
	// Access Token 有效期单位秒
	AccessTokenTimeToLiveSeconds int64 `protobuf:"varint,14,opt,name=access_token_time_to_live_seconds,json=accessTokenTimeToLiveSeconds,proto3" json:"access_token_time_to_live_seconds,omitempty"`
	// Refresh Token 有效期单位秒
	RefreshTokenTimeToLiveSeconds int64 `protobuf:"varint,15,opt,name=refresh_token_time_to_live_seconds,json=refreshTokenTimeToLiveSeconds,proto3" json:"refresh_token_time_to_live_seconds,omitempty"`
	// Authorization Code 有效期单位秒
	AuthorizationCodeTimeToLiveSeconds int64 `protobuf:"varint,16,opt,name=authorization_code_time_to_live_seconds,json=authorizationCodeTimeToLiveSeconds,proto3" json:"authorization_code_time_to_live_seconds,omitempty"`
	// 状态（1：有效；0：无效）
	Status int32 `protobuf:"varint,17,opt,name=status,proto3" json:"status,omitempty"`
	// 删除标记
	DelFlag int32 `protobuf:"varint,18,opt,name=del_flag,json=delFlag,proto3" json:"del_flag,omitempty"`
	// 创建人ID
	CreateUserId int64 `protobuf:"varint,19,opt,name=create_user_id,json=createUserId,proto3" json:"create_user_id,omitempty"`
	// 修改人ID
	UpdateUserId int64 `protobuf:"varint,20,opt,name=update_user_id,json=updateUserId,proto3" json:"update_user_id,omitempty"`
	// 创建时间
	CreateTime int64 `protobuf:"varint,21,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// 更新时间
	UpdateTime int64 `protobuf:"varint,22,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// 错误信息
	ErrorMsg      string `protobuf:"bytes,23,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDetails) Reset() {
	*x = ClientDetails{}
	mi := &file_proto_client_detail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDetails) ProtoMessage() {}

func (x *ClientDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_detail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDetails.ProtoReflect.Descriptor instead.
func (*ClientDetails) Descriptor() ([]byte, []int) {
	return file_proto_client_detail_proto_rawDescGZIP(), []int{1}
}

func (x *ClientDetails) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClientDetails) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ClientDetails) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientDetails) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *ClientDetails) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *ClientDetails) GetClientIdIssuedAt() int64 {
	if x != nil {
		return x.ClientIdIssuedAt
	}
	return 0
}

func (x *ClientDetails) GetClientSecretExpiresAt() int64 {
	if x != nil {
		return x.ClientSecretExpiresAt
	}
	return 0
}

func (x *ClientDetails) GetClientAuthenticationMethods() []string {
	if x != nil {
		return x.ClientAuthenticationMethods
	}
	return nil
}

func (x *ClientDetails) GetAuthorizationGrantTypes() []string {
	if x != nil {
		return x.AuthorizationGrantTypes
	}
	return nil
}

func (x *ClientDetails) GetRedirectUris() []string {
	if x != nil {
		return x.RedirectUris
	}
	return nil
}

func (x *ClientDetails) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ClientDetails) GetClientSettings() string {
	if x != nil {
		return x.ClientSettings
	}
	return ""
}

func (x *ClientDetails) GetTokenSettings() string {
	if x != nil {
		return x.TokenSettings
	}
	return ""
}

func (x *ClientDetails) GetAccessTokenTimeToLiveSeconds() int64 {
	if x != nil {
		return x.AccessTokenTimeToLiveSeconds
	}
	return 0
}

func (x *ClientDetails) GetRefreshTokenTimeToLiveSeconds() int64 {
	if x != nil {
		return x.RefreshTokenTimeToLiveSeconds
	}
	return 0
}

func (x *ClientDetails) GetAuthorizationCodeTimeToLiveSeconds() int64 {
	if x != nil {
		return x.AuthorizationCodeTimeToLiveSeconds
	}
	return 0
}

func (x *ClientDetails) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ClientDetails) GetDelFlag() int32 {
	if x != nil {
		return x.DelFlag
	}
	return 0
}

func (x *ClientDetails) GetCreateUserId() int64 {
	if x != nil {
		return x.CreateUserId
	}
	return 0
}

func (x *ClientDetails) GetUpdateUserId() int64 {
	if x != nil {
		return x.UpdateUserId
	}
	return 0
}

func (x *ClientDetails) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ClientDetails) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *ClientDetails) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_proto_client_detail_proto protoreflect.FileDescriptor

const file_proto_client_detail_proto_rawDesc = "" +
	"\n" +
	"\x19proto/client_detail.proto\x12\rxyz.grpc.upms\x1a\x12proto/common.proto\"/\n" +
	"\x10GetByClientIdReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xdb\a\n" +
	"\rClientDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x04 \x01(\tR\fclientSecret\x12\x1f\n" +
	"\vclient_name\x18\x05 \x01(\tR\n" +
	"clientName\x12-\n" +
	"\x13client_id_issued_at\x18\x06 \x01(\x03R\x10clientIdIssuedAt\x127\n" +
	"\x18client_secret_expires_at\x18\a \x01(\x03R\x15clientSecretExpiresAt\x12B\n" +
	"\x1dclient_authentication_methods\x18\b \x03(\tR\x1bclientAuthenticationMethods\x12:\n" +
	"\x19authorization_grant_types\x18\t \x03(\tR\x17authorizationGrantTypes\x12#\n" +
	"\rredirect_uris\x18\n" +
	" \x03(\tR\fredirectUris\x12\x16\n" +
	"\x06scopes\x18\v \x03(\tR\x06scopes\x12'\n" +
	"\x0fclient_settings\x18\f \x01(\tR\x0eclientSettings\x12%\n" +
	"\x0etoken_settings\x18\r \x01(\tR\rtokenSettings\x12G\n" +
	"!access_token_time_to_live_seconds\x18\x0e \x01(\x03R\x1caccessTokenTimeToLiveSeconds\x12I\n" +
	"\"refresh_token_time_to_live_seconds\x18\x0f \x01(\x03R\x1drefreshTokenTimeToLiveSeconds\x12S\n" +
	"'authorization_code_time_to_live_seconds\x18\x10 \x01(\x03R\"authorizationCodeTimeToLiveSeconds\x12\x16\n" +
	"\x06status\x18\x11 \x01(\x05R\x06status\x12\x19\n" +
	"\bdel_flag\x18\x12 \x01(\x05R\adelFlag\x12$\n" +
	"\x0ecreate_user_id\x18\x13 \x01(\x03R\fcreateUserId\x12$\n" +
	"\x0eupdate_user_id\x18\x14 \x01(\x03R\fupdateUserId\x12\x1f\n" +
	"\vcreate_time\x18\x15 \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x16 \x01(\x03R\n" +
	"updateTime\x12\x1b\n" +
	"\terror_msg\x18\x17 \x01(\tR\berrorMsg2\xf4\x01\n" +
	"\x10ClientDetailsSvc\x12H\n" +
	"\n" +
	"SaveEntity\x12\x1c.xyz.grpc.upms.ClientDetails\x1a\x1c.xyz.grpc.upms.ClientDetails\x12F\n" +
	"\bFindById\x12\x1c.xyz.grpc.common.FindByIdReq\x1a\x1c.xyz.grpc.upms.ClientDetails\x12N\n" +
	"\rGetByClientId\x12\x1f.xyz.grpc.upms.GetByClientIdReq\x1a\x1c.xyz.grpc.upms.ClientDetailsBV\n" +
	"\x15xyz.grpc.user.detailsB\x12ClientDetailsProtoP\x01Z'github.com/lucky-xin/xyz-oauth2-go/upmsb\x06proto3"

var (
	file_proto_client_detail_proto_rawDescOnce sync.Once
	file_proto_client_detail_proto_rawDescData []byte
)

func file_proto_client_detail_proto_rawDescGZIP() []byte {
	file_proto_client_detail_proto_rawDescOnce.Do(func() {
		file_proto_client_detail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_client_detail_proto_rawDesc), len(file_proto_client_detail_proto_rawDesc)))
	})
	return file_proto_client_detail_proto_rawDescData
}

var file_proto_client_detail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_client_detail_proto_goTypes = []any{
	(*GetByClientIdReq)(nil), // 0: xyz.grpc.upms.GetByClientIdReq
	(*ClientDetails)(nil),    // 1: xyz.grpc.upms.ClientDetails
	(*FindByIdReq)(nil),      // 2: xyz.grpc.common.FindByIdReq
}
var file_proto_client_detail_proto_depIdxs = []int32{
	1, // 0: xyz.grpc.upms.ClientDetailsSvc.SaveEntity:input_type -> xyz.grpc.upms.ClientDetails
	2, // 1: xyz.grpc.upms.ClientDetailsSvc.FindById:input_type -> xyz.grpc.common.FindByIdReq
	0, // 2: xyz.grpc.upms.ClientDetailsSvc.GetByClientId:input_type -> xyz.grpc.upms.GetByClientIdReq
	1, // 3: xyz.grpc.upms.ClientDetailsSvc.SaveEntity:output_type -> xyz.grpc.upms.ClientDetails
	1, // 4: xyz.grpc.upms.ClientDetailsSvc.FindById:output_type -> xyz.grpc.upms.ClientDetails
	1, // 5: xyz.grpc.upms.ClientDetailsSvc.GetByClientId:output_type -> xyz.grpc.upms.ClientDetails
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_client_detail_proto_init() }
func file_proto_client_detail_proto_init() {
	if File_proto_client_detail_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_client_detail_proto_rawDesc), len(file_proto_client_detail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_client_detail_proto_goTypes,
		DependencyIndexes: file_proto_client_detail_proto_depIdxs,
		MessageInfos:      file_proto_client_detail_proto_msgTypes,
	}.Build()
	File_proto_client_detail_proto = out.File
	file_proto_client_detail_proto_goTypes = nil
	file_proto_client_detail_proto_depIdxs = nil
}
