// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.0
// source: proto/encryption_config_detail.proto

package upms

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EncryptionConfigDetailsSvc_LoadByAppId_FullMethodName    = "/xyz.grpc.upms.EncryptionConfigDetailsSvc/LoadByAppId"
	EncryptionConfigDetailsSvc_LoadByClientId_FullMethodName = "/xyz.grpc.upms.EncryptionConfigDetailsSvc/LoadByClientId"
	EncryptionConfigDetailsSvc_ListAppId_FullMethodName      = "/xyz.grpc.upms.EncryptionConfigDetailsSvc/ListAppId"
)

// EncryptionConfigDetailsSvcClient is the client API for EncryptionConfigDetailsSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 加密配置服务
type EncryptionConfigDetailsSvcClient interface {
	// 根据AppId查询加密配置
	LoadByAppId(ctx context.Context, in *LoadByAppIdReq, opts ...grpc.CallOption) (*EncryptionConfigDetails, error)
	// 根据ClientId查询加密配置
	LoadByClientId(ctx context.Context, in *LoadByClientIdReq, opts ...grpc.CallOption) (*EncryptionConfigDetails, error)
	// 根据用户名获取AppId列表
	ListAppId(ctx context.Context, in *ListAppIdReq, opts ...grpc.CallOption) (*ListAppIdResp, error)
}

type encryptionConfigDetailsSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewEncryptionConfigDetailsSvcClient(cc grpc.ClientConnInterface) EncryptionConfigDetailsSvcClient {
	return &encryptionConfigDetailsSvcClient{cc}
}

func (c *encryptionConfigDetailsSvcClient) LoadByAppId(ctx context.Context, in *LoadByAppIdReq, opts ...grpc.CallOption) (*EncryptionConfigDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptionConfigDetails)
	err := c.cc.Invoke(ctx, EncryptionConfigDetailsSvc_LoadByAppId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encryptionConfigDetailsSvcClient) LoadByClientId(ctx context.Context, in *LoadByClientIdReq, opts ...grpc.CallOption) (*EncryptionConfigDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptionConfigDetails)
	err := c.cc.Invoke(ctx, EncryptionConfigDetailsSvc_LoadByClientId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encryptionConfigDetailsSvcClient) ListAppId(ctx context.Context, in *ListAppIdReq, opts ...grpc.CallOption) (*ListAppIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAppIdResp)
	err := c.cc.Invoke(ctx, EncryptionConfigDetailsSvc_ListAppId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EncryptionConfigDetailsSvcServer is the server API for EncryptionConfigDetailsSvc service.
// All implementations must embed UnimplementedEncryptionConfigDetailsSvcServer
// for forward compatibility.
//
// 加密配置服务
type EncryptionConfigDetailsSvcServer interface {
	// 根据AppId查询加密配置
	LoadByAppId(context.Context, *LoadByAppIdReq) (*EncryptionConfigDetails, error)
	// 根据ClientId查询加密配置
	LoadByClientId(context.Context, *LoadByClientIdReq) (*EncryptionConfigDetails, error)
	// 根据用户名获取AppId列表
	ListAppId(context.Context, *ListAppIdReq) (*ListAppIdResp, error)
	mustEmbedUnimplementedEncryptionConfigDetailsSvcServer()
}

// UnimplementedEncryptionConfigDetailsSvcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEncryptionConfigDetailsSvcServer struct{}

func (UnimplementedEncryptionConfigDetailsSvcServer) LoadByAppId(context.Context, *LoadByAppIdReq) (*EncryptionConfigDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadByAppId not implemented")
}
func (UnimplementedEncryptionConfigDetailsSvcServer) LoadByClientId(context.Context, *LoadByClientIdReq) (*EncryptionConfigDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadByClientId not implemented")
}
func (UnimplementedEncryptionConfigDetailsSvcServer) ListAppId(context.Context, *ListAppIdReq) (*ListAppIdResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAppId not implemented")
}
func (UnimplementedEncryptionConfigDetailsSvcServer) mustEmbedUnimplementedEncryptionConfigDetailsSvcServer() {
}
func (UnimplementedEncryptionConfigDetailsSvcServer) testEmbeddedByValue() {}

// UnsafeEncryptionConfigDetailsSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EncryptionConfigDetailsSvcServer will
// result in compilation errors.
type UnsafeEncryptionConfigDetailsSvcServer interface {
	mustEmbedUnimplementedEncryptionConfigDetailsSvcServer()
}

func RegisterEncryptionConfigDetailsSvcServer(s grpc.ServiceRegistrar, srv EncryptionConfigDetailsSvcServer) {
	// If the following call panics, it indicates UnimplementedEncryptionConfigDetailsSvcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EncryptionConfigDetailsSvc_ServiceDesc, srv)
}

func _EncryptionConfigDetailsSvc_LoadByAppId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadByAppIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptionConfigDetailsSvcServer).LoadByAppId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncryptionConfigDetailsSvc_LoadByAppId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptionConfigDetailsSvcServer).LoadByAppId(ctx, req.(*LoadByAppIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncryptionConfigDetailsSvc_LoadByClientId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadByClientIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptionConfigDetailsSvcServer).LoadByClientId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncryptionConfigDetailsSvc_LoadByClientId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptionConfigDetailsSvcServer).LoadByClientId(ctx, req.(*LoadByClientIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncryptionConfigDetailsSvc_ListAppId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptionConfigDetailsSvcServer).ListAppId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncryptionConfigDetailsSvc_ListAppId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptionConfigDetailsSvcServer).ListAppId(ctx, req.(*ListAppIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// EncryptionConfigDetailsSvc_ServiceDesc is the grpc.ServiceDesc for EncryptionConfigDetailsSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EncryptionConfigDetailsSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xyz.grpc.upms.EncryptionConfigDetailsSvc",
	HandlerType: (*EncryptionConfigDetailsSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadByAppId",
			Handler:    _EncryptionConfigDetailsSvc_LoadByAppId_Handler,
		},
		{
			MethodName: "LoadByClientId",
			Handler:    _EncryptionConfigDetailsSvc_LoadByClientId_Handler,
		},
		{
			MethodName: "ListAppId",
			Handler:    _EncryptionConfigDetailsSvc_ListAppId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/encryption_config_detail.proto",
}
