// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: proto/encryption_config_detail.proto

package upms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 根据AppId查询请求
type LoadByAppIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadByAppIdReq) Reset() {
	*x = LoadByAppIdReq{}
	mi := &file_proto_encryption_config_detail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadByAppIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadByAppIdReq) ProtoMessage() {}

func (x *LoadByAppIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encryption_config_detail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadByAppIdReq.ProtoReflect.Descriptor instead.
func (*LoadByAppIdReq) Descriptor() ([]byte, []int) {
	return file_proto_encryption_config_detail_proto_rawDescGZIP(), []int{0}
}

func (x *LoadByAppIdReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

// 根据ClientId查询请求
type LoadByClientIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadByClientIdReq) Reset() {
	*x = LoadByClientIdReq{}
	mi := &file_proto_encryption_config_detail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadByClientIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadByClientIdReq) ProtoMessage() {}

func (x *LoadByClientIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encryption_config_detail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadByClientIdReq.ProtoReflect.Descriptor instead.
func (*LoadByClientIdReq) Descriptor() ([]byte, []int) {
	return file_proto_encryption_config_detail_proto_rawDescGZIP(), []int{1}
}

func (x *LoadByClientIdReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// 根据用户名获取AppId列表请求
type ListAppIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppIdReq) Reset() {
	*x = ListAppIdReq{}
	mi := &file_proto_encryption_config_detail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppIdReq) ProtoMessage() {}

func (x *ListAppIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encryption_config_detail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppIdReq.ProtoReflect.Descriptor instead.
func (*ListAppIdReq) Descriptor() ([]byte, []int) {
	return file_proto_encryption_config_detail_proto_rawDescGZIP(), []int{2}
}

func (x *ListAppIdReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

// AppId列表响应
type ListAppIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppIds        []string               `protobuf:"bytes,1,rep,name=app_ids,json=appIds,proto3" json:"app_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppIdResp) Reset() {
	*x = ListAppIdResp{}
	mi := &file_proto_encryption_config_detail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppIdResp) ProtoMessage() {}

func (x *ListAppIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encryption_config_detail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppIdResp.ProtoReflect.Descriptor instead.
func (*ListAppIdResp) Descriptor() ([]byte, []int) {
	return file_proto_encryption_config_detail_proto_rawDescGZIP(), []int{3}
}

func (x *ListAppIdResp) GetAppIds() []string {
	if x != nil {
		return x.AppIds
	}
	return nil
}

// 加密配置响应
type EncryptionConfigDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AppId
	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// AppSecret
	AppSecret string `protobuf:"bytes,2,opt,name=app_secret,json=appSecret,proto3" json:"app_secret,omitempty"`
	// 客户端ID
	ClientId string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// 客户端密钥
	ClientSecret string `protobuf:"bytes,4,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	// 绑定用户名称
	Username string `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	// AES 数字签名key id
	AesKeyId int64 `protobuf:"varint,6,opt,name=aes_key_id,json=aesKeyId,proto3" json:"aes_key_id,omitempty"`
	// EC 数字签名key id
	EcKeyId int64 `protobuf:"varint,7,opt,name=ec_key_id,json=ecKeyId,proto3" json:"ec_key_id,omitempty"`
	// RSA 加密解码配置id
	RsaKeyId int64 `protobuf:"varint,8,opt,name=rsa_key_id,json=rsaKeyId,proto3" json:"rsa_key_id,omitempty"`
	// SM2 加密解码配置id
	Sm2KeyId int64 `protobuf:"varint,9,opt,name=sm2_key_id,json=sm2KeyId,proto3" json:"sm2_key_id,omitempty"`
	// AES 数字签名key
	AesKey []byte `protobuf:"bytes,10,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`
	// AES IV key
	AesIv []byte `protobuf:"bytes,11,opt,name=aes_iv,json=aesIv,proto3" json:"aes_iv,omitempty"`
	// RSA 公钥
	RsaPublicKey []byte `protobuf:"bytes,12,opt,name=rsa_public_key,json=rsaPublicKey,proto3" json:"rsa_public_key,omitempty"`
	// RSA 私钥
	RsaPrivateKey []byte `protobuf:"bytes,13,opt,name=rsa_private_key,json=rsaPrivateKey,proto3" json:"rsa_private_key,omitempty"`
	// SM2 公钥
	Sm2PublicKey []byte `protobuf:"bytes,14,opt,name=sm2_public_key,json=sm2PublicKey,proto3" json:"sm2_public_key,omitempty"`
	// SM2 私钥
	Sm2PrivateKey []byte `protobuf:"bytes,15,opt,name=sm2_private_key,json=sm2PrivateKey,proto3" json:"sm2_private_key,omitempty"`
	// EC 公钥
	EcPublicKey []byte `protobuf:"bytes,16,opt,name=ec_public_key,json=ecPublicKey,proto3" json:"ec_public_key,omitempty"`
	// EC 私钥
	EcPrivateKey []byte `protobuf:"bytes,17,opt,name=ec_private_key,json=ecPrivateKey,proto3" json:"ec_private_key,omitempty"`
	// 数字签名token超时（单位毫秒）
	SignTimeoutMillis int32 `protobuf:"varint,18,opt,name=sign_timeout_millis,json=signTimeoutMillis,proto3" json:"sign_timeout_millis,omitempty"`
	// 错误信息
	ErrorMsg      string `protobuf:"bytes,19,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptionConfigDetails) Reset() {
	*x = EncryptionConfigDetails{}
	mi := &file_proto_encryption_config_detail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptionConfigDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptionConfigDetails) ProtoMessage() {}

func (x *EncryptionConfigDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encryption_config_detail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptionConfigDetails.ProtoReflect.Descriptor instead.
func (*EncryptionConfigDetails) Descriptor() ([]byte, []int) {
	return file_proto_encryption_config_detail_proto_rawDescGZIP(), []int{4}
}

func (x *EncryptionConfigDetails) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *EncryptionConfigDetails) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

func (x *EncryptionConfigDetails) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *EncryptionConfigDetails) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *EncryptionConfigDetails) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *EncryptionConfigDetails) GetAesKeyId() int64 {
	if x != nil {
		return x.AesKeyId
	}
	return 0
}

func (x *EncryptionConfigDetails) GetEcKeyId() int64 {
	if x != nil {
		return x.EcKeyId
	}
	return 0
}

func (x *EncryptionConfigDetails) GetRsaKeyId() int64 {
	if x != nil {
		return x.RsaKeyId
	}
	return 0
}

func (x *EncryptionConfigDetails) GetSm2KeyId() int64 {
	if x != nil {
		return x.Sm2KeyId
	}
	return 0
}

func (x *EncryptionConfigDetails) GetAesKey() []byte {
	if x != nil {
		return x.AesKey
	}
	return nil
}

func (x *EncryptionConfigDetails) GetAesIv() []byte {
	if x != nil {
		return x.AesIv
	}
	return nil
}

func (x *EncryptionConfigDetails) GetRsaPublicKey() []byte {
	if x != nil {
		return x.RsaPublicKey
	}
	return nil
}

func (x *EncryptionConfigDetails) GetRsaPrivateKey() []byte {
	if x != nil {
		return x.RsaPrivateKey
	}
	return nil
}

func (x *EncryptionConfigDetails) GetSm2PublicKey() []byte {
	if x != nil {
		return x.Sm2PublicKey
	}
	return nil
}

func (x *EncryptionConfigDetails) GetSm2PrivateKey() []byte {
	if x != nil {
		return x.Sm2PrivateKey
	}
	return nil
}

func (x *EncryptionConfigDetails) GetEcPublicKey() []byte {
	if x != nil {
		return x.EcPublicKey
	}
	return nil
}

func (x *EncryptionConfigDetails) GetEcPrivateKey() []byte {
	if x != nil {
		return x.EcPrivateKey
	}
	return nil
}

func (x *EncryptionConfigDetails) GetSignTimeoutMillis() int32 {
	if x != nil {
		return x.SignTimeoutMillis
	}
	return 0
}

func (x *EncryptionConfigDetails) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_proto_encryption_config_detail_proto protoreflect.FileDescriptor

const file_proto_encryption_config_detail_proto_rawDesc = "" +
	"\n" +
	"$proto/encryption_config_detail.proto\x12\rxyz.grpc.upms\"'\n" +
	"\x0eLoadByAppIdReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"0\n" +
	"\x11LoadByClientIdReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"+\n" +
	"\fListAppIdReq\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\"(\n" +
	"\rListAppIdResp\x12\x17\n" +
	"\aapp_ids\x18\x01 \x03(\tR\x06appIds\"\x86\x05\n" +
	"\x17EncryptionConfigDetails\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"app_secret\x18\x02 \x01(\tR\tappSecret\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x04 \x01(\tR\fclientSecret\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1c\n" +
	"\n" +
	"aes_key_id\x18\x06 \x01(\x03R\baesKeyId\x12\x1a\n" +
	"\tec_key_id\x18\a \x01(\x03R\aecKeyId\x12\x1c\n" +
	"\n" +
	"rsa_key_id\x18\b \x01(\x03R\brsaKeyId\x12\x1c\n" +
	"\n" +
	"sm2_key_id\x18\t \x01(\x03R\bsm2KeyId\x12\x17\n" +
	"\aaes_key\x18\n" +
	" \x01(\fR\x06aesKey\x12\x15\n" +
	"\x06aes_iv\x18\v \x01(\fR\x05aesIv\x12$\n" +
	"\x0ersa_public_key\x18\f \x01(\fR\frsaPublicKey\x12&\n" +
	"\x0frsa_private_key\x18\r \x01(\fR\rrsaPrivateKey\x12$\n" +
	"\x0esm2_public_key\x18\x0e \x01(\fR\fsm2PublicKey\x12&\n" +
	"\x0fsm2_private_key\x18\x0f \x01(\fR\rsm2PrivateKey\x12\"\n" +
	"\rec_public_key\x18\x10 \x01(\fR\vecPublicKey\x12$\n" +
	"\x0eec_private_key\x18\x11 \x01(\fR\fecPrivateKey\x12.\n" +
	"\x13sign_timeout_millis\x18\x12 \x01(\x05R\x11signTimeoutMillis\x12\x1b\n" +
	"\terror_msg\x18\x13 \x01(\tR\berrorMsg2\x96\x02\n" +
	"\x1aEncryptionConfigDetailsSvc\x12T\n" +
	"\vLoadByAppId\x12\x1d.xyz.grpc.upms.LoadByAppIdReq\x1a&.xyz.grpc.upms.EncryptionConfigDetails\x12Z\n" +
	"\x0eLoadByClientId\x12 .xyz.grpc.upms.LoadByClientIdReq\x1a&.xyz.grpc.upms.EncryptionConfigDetails\x12F\n" +
	"\tListAppId\x12\x1b.xyz.grpc.upms.ListAppIdReq\x1a\x1c.xyz.grpc.upms.ListAppIdRespBm\n" +
	"\"xyz.grpc.encryption.config.detailsB\x1cEncryptionConfigDetailsProtoP\x01Z'github.com/lucky-xin/xyz-oauth2-go/upmsb\x06proto3"

var (
	file_proto_encryption_config_detail_proto_rawDescOnce sync.Once
	file_proto_encryption_config_detail_proto_rawDescData []byte
)

func file_proto_encryption_config_detail_proto_rawDescGZIP() []byte {
	file_proto_encryption_config_detail_proto_rawDescOnce.Do(func() {
		file_proto_encryption_config_detail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_encryption_config_detail_proto_rawDesc), len(file_proto_encryption_config_detail_proto_rawDesc)))
	})
	return file_proto_encryption_config_detail_proto_rawDescData
}

var file_proto_encryption_config_detail_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_encryption_config_detail_proto_goTypes = []any{
	(*LoadByAppIdReq)(nil),          // 0: xyz.grpc.upms.LoadByAppIdReq
	(*LoadByClientIdReq)(nil),       // 1: xyz.grpc.upms.LoadByClientIdReq
	(*ListAppIdReq)(nil),            // 2: xyz.grpc.upms.ListAppIdReq
	(*ListAppIdResp)(nil),           // 3: xyz.grpc.upms.ListAppIdResp
	(*EncryptionConfigDetails)(nil), // 4: xyz.grpc.upms.EncryptionConfigDetails
}
var file_proto_encryption_config_detail_proto_depIdxs = []int32{
	0, // 0: xyz.grpc.upms.EncryptionConfigDetailsSvc.LoadByAppId:input_type -> xyz.grpc.upms.LoadByAppIdReq
	1, // 1: xyz.grpc.upms.EncryptionConfigDetailsSvc.LoadByClientId:input_type -> xyz.grpc.upms.LoadByClientIdReq
	2, // 2: xyz.grpc.upms.EncryptionConfigDetailsSvc.ListAppId:input_type -> xyz.grpc.upms.ListAppIdReq
	4, // 3: xyz.grpc.upms.EncryptionConfigDetailsSvc.LoadByAppId:output_type -> xyz.grpc.upms.EncryptionConfigDetails
	4, // 4: xyz.grpc.upms.EncryptionConfigDetailsSvc.LoadByClientId:output_type -> xyz.grpc.upms.EncryptionConfigDetails
	3, // 5: xyz.grpc.upms.EncryptionConfigDetailsSvc.ListAppId:output_type -> xyz.grpc.upms.ListAppIdResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_encryption_config_detail_proto_init() }
func file_proto_encryption_config_detail_proto_init() {
	if File_proto_encryption_config_detail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_encryption_config_detail_proto_rawDesc), len(file_proto_encryption_config_detail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_encryption_config_detail_proto_goTypes,
		DependencyIndexes: file_proto_encryption_config_detail_proto_depIdxs,
		MessageInfos:      file_proto_encryption_config_detail_proto_msgTypes,
	}.Build()
	File_proto_encryption_config_detail_proto = out.File
	file_proto_encryption_config_detail_proto_goTypes = nil
	file_proto_encryption_config_detail_proto_depIdxs = nil
}
