// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: oauth2.proto

package upms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// encryption key type
type EncryptionKeyType int32

const (
	EncryptionKeyType_RSA EncryptionKeyType = 0
	EncryptionKeyType_EC  EncryptionKeyType = 1
	EncryptionKeyType_AES EncryptionKeyType = 2
	EncryptionKeyType_SM2 EncryptionKeyType = 3
)

// Enum value maps for EncryptionKeyType.
var (
	EncryptionKeyType_name = map[int32]string{
		0: "RSA",
		1: "EC",
		2: "AES",
		3: "SM2",
	}
	EncryptionKeyType_value = map[string]int32{
		"RSA": 0,
		"EC":  1,
		"AES": 2,
		"SM2": 3,
	}
)

func (x EncryptionKeyType) Enum() *EncryptionKeyType {
	p := new(EncryptionKeyType)
	*p = x
	return p
}

func (x EncryptionKeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncryptionKeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_oauth2_proto_enumTypes[0].Descriptor()
}

func (EncryptionKeyType) Type() protoreflect.EnumType {
	return &file_oauth2_proto_enumTypes[0]
}

func (x EncryptionKeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncryptionKeyType.Descriptor instead.
func (EncryptionKeyType) EnumDescriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{0}
}

// 空请求/响应
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_oauth2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{0}
}

// token key
type OAuth2TokenKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token key
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// 密钥id
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// 加密算法
	Alg           string `protobuf:"bytes,3,opt,name=alg,proto3" json:"alg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2TokenKey) Reset() {
	*x = OAuth2TokenKey{}
	mi := &file_oauth2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2TokenKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2TokenKey) ProtoMessage() {}

func (x *OAuth2TokenKey) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2TokenKey.ProtoReflect.Descriptor instead.
func (*OAuth2TokenKey) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{1}
}

func (x *OAuth2TokenKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *OAuth2TokenKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OAuth2TokenKey) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

// 获取密钥请求
type SecretKeyReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 密钥类型
	Type EncryptionKeyType `protobuf:"varint,1,opt,name=type,proto3,enum=com.unified.grpc.oauth2.EncryptionKeyType" json:"type,omitempty"`
	// 随机串
	Random        string `protobuf:"bytes,2,opt,name=random,proto3" json:"random,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretKeyReq) Reset() {
	*x = SecretKeyReq{}
	mi := &file_oauth2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretKeyReq) ProtoMessage() {}

func (x *SecretKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretKeyReq.ProtoReflect.Descriptor instead.
func (*SecretKeyReq) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{2}
}

func (x *SecretKeyReq) GetType() EncryptionKeyType {
	if x != nil {
		return x.Type
	}
	return EncryptionKeyType_RSA
}

func (x *SecretKeyReq) GetRandom() string {
	if x != nil {
		return x.Random
	}
	return ""
}

// secret key
type SecretKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 密钥类型
	Type EncryptionKeyType `protobuf:"varint,1,opt,name=type,proto3,enum=com.unified.grpc.oauth2.EncryptionKeyType" json:"type,omitempty"`
	// 公钥
	PublicKey []byte `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	// 私钥
	PrivateKey []byte `protobuf:"bytes,3,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	// 错误信息
	// 错误信息
	ErrorMsg      string `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretKey) Reset() {
	*x = SecretKey{}
	mi := &file_oauth2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretKey) ProtoMessage() {}

func (x *SecretKey) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretKey.ProtoReflect.Descriptor instead.
func (*SecretKey) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{3}
}

func (x *SecretKey) GetType() EncryptionKeyType {
	if x != nil {
		return x.Type
	}
	return EncryptionKeyType_RSA
}

func (x *SecretKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *SecretKey) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *SecretKey) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 登录参数
type LoginProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 该字段为 客户端id
	ClientId string `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	// 该字段为 客户端密钥
	ClientSecret string `protobuf:"bytes,2,opt,name=clientSecret,proto3" json:"clientSecret,omitempty"`
	// 授权方式password,refresh_token,authorization_code,client_credentials。默认为password
	GrantType string `protobuf:"bytes,3,opt,name=grantType,proto3" json:"grantType,omitempty"`
	// The scope of the token. default read_write
	Scope string `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	// 登录用户名
	Username string `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	// 登录密码
	Password      string `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginProfile) Reset() {
	*x = LoginProfile{}
	mi := &file_oauth2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginProfile) ProtoMessage() {}

func (x *LoginProfile) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginProfile.ProtoReflect.Descriptor instead.
func (*LoginProfile) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{4}
}

func (x *LoginProfile) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LoginProfile) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *LoginProfile) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *LoginProfile) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *LoginProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginProfile) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 登录返回token
type OAuth2Token struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token value
	AccessToken string `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	// The token type, as introduced in draft 11 of the OAuth 2 spec.
	TokenType string `protobuf:"bytes,2,opt,name=tokenType,proto3" json:"tokenType,omitempty"`
	// The instant the token expires.
	IssuedAt int32 `protobuf:"varint,3,opt,name=issuedAt,proto3" json:"issuedAt,omitempty"`
	// Expires at
	ExpiresAt int32 `protobuf:"varint,5,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	// The refresh token associated with the access token, if any.
	RefreshToken string `protobuf:"bytes,6,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	// The scope of the token.
	Scope []string `protobuf:"bytes,7,rep,name=scope,proto3" json:"scope,omitempty"`
	// Additional information that token granters would like to add to the token, e.g. to support new token types.
	AdditionalInfo map[string]string `protobuf:"bytes,8,rep,name=additionalInfo,proto3" json:"additionalInfo,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 错误信息
	ErrorMsg      string `protobuf:"bytes,9,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2Token) Reset() {
	*x = OAuth2Token{}
	mi := &file_oauth2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2Token) ProtoMessage() {}

func (x *OAuth2Token) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2Token.ProtoReflect.Descriptor instead.
func (*OAuth2Token) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{5}
}

func (x *OAuth2Token) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *OAuth2Token) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *OAuth2Token) GetIssuedAt() int32 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *OAuth2Token) GetExpiresAt() int32 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *OAuth2Token) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *OAuth2Token) GetScope() []string {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *OAuth2Token) GetAdditionalInfo() map[string]string {
	if x != nil {
		return x.AdditionalInfo
	}
	return nil
}

func (x *OAuth2Token) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type LogoutProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutProfile) Reset() {
	*x = LogoutProfile{}
	mi := &file_oauth2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutProfile) ProtoMessage() {}

func (x *LogoutProfile) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutProfile.ProtoReflect.Descriptor instead.
func (*LogoutProfile) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutProfile) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 检查令牌请求
type CheckTokenReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTokenReq) Reset() {
	*x = CheckTokenReq{}
	mi := &file_oauth2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenReq) ProtoMessage() {}

func (x *CheckTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenReq.ProtoReflect.Descriptor instead.
func (*CheckTokenReq) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{7}
}

func (x *CheckTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// OAuth2访问令牌响应
type OAuth2AccessTokenResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 访问令牌
	AccessToken *OAuth2Token `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	// 刷新令牌值
	RefreshToken string `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	// 额外参数
	AdditionalParameters map[string]string `protobuf:"bytes,3,rep,name=additionalParameters,proto3" json:"additionalParameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 错误信息
	ErrorMsg      string `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2AccessTokenResp) Reset() {
	*x = OAuth2AccessTokenResp{}
	mi := &file_oauth2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2AccessTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2AccessTokenResp) ProtoMessage() {}

func (x *OAuth2AccessTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2AccessTokenResp.ProtoReflect.Descriptor instead.
func (*OAuth2AccessTokenResp) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{8}
}

func (x *OAuth2AccessTokenResp) GetAccessToken() *OAuth2Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *OAuth2AccessTokenResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *OAuth2AccessTokenResp) GetAdditionalParameters() map[string]string {
	if x != nil {
		return x.AdditionalParameters
	}
	return nil
}

func (x *OAuth2AccessTokenResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_oauth2_proto protoreflect.FileDescriptor

const file_oauth2_proto_rawDesc = "" +
	"\n" +
	"\foauth2.proto\x12\x17com.unified.grpc.oauth2\"\a\n" +
	"\x05Empty\"D\n" +
	"\x0eOAuth2TokenKey\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x10\n" +
	"\x03alg\x18\x03 \x01(\tR\x03alg\"f\n" +
	"\fSecretKeyReq\x12>\n" +
	"\x04type\x18\x01 \x01(\x0e2*.com.unified.grpc.oauth2.EncryptionKeyTypeR\x04type\x12\x16\n" +
	"\x06random\x18\x02 \x01(\tR\x06random\"\xa6\x01\n" +
	"\tSecretKey\x12>\n" +
	"\x04type\x18\x01 \x01(\x0e2*.com.unified.grpc.oauth2.EncryptionKeyTypeR\x04type\x12\x1c\n" +
	"\tpublicKey\x18\x02 \x01(\fR\tpublicKey\x12\x1e\n" +
	"\n" +
	"privateKey\x18\x03 \x01(\fR\n" +
	"privateKey\x12\x1b\n" +
	"\terror_msg\x18\x04 \x01(\tR\berrorMsg\"\xba\x01\n" +
	"\fLoginProfile\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12\"\n" +
	"\fclientSecret\x18\x02 \x01(\tR\fclientSecret\x12\x1c\n" +
	"\tgrantType\x18\x03 \x01(\tR\tgrantType\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\"\x83\x03\n" +
	"\vOAuth2Token\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x1c\n" +
	"\ttokenType\x18\x02 \x01(\tR\ttokenType\x12\x1a\n" +
	"\bissuedAt\x18\x03 \x01(\x05R\bissuedAt\x12\x1c\n" +
	"\texpiresAt\x18\x05 \x01(\x05R\texpiresAt\x12\"\n" +
	"\frefreshToken\x18\x06 \x01(\tR\frefreshToken\x12\x14\n" +
	"\x05scope\x18\a \x03(\tR\x05scope\x12`\n" +
	"\x0eadditionalInfo\x18\b \x03(\v28.com.unified.grpc.oauth2.OAuth2Token.AdditionalInfoEntryR\x0eadditionalInfo\x12\x1b\n" +
	"\terror_msg\x18\t \x01(\tR\berrorMsg\x1aA\n" +
	"\x13AdditionalInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"%\n" +
	"\rLogoutProfile\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"%\n" +
	"\rCheckTokenReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xe7\x02\n" +
	"\x15OAuth2AccessTokenResp\x12F\n" +
	"\vaccessToken\x18\x01 \x01(\v2$.com.unified.grpc.oauth2.OAuth2TokenR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\x12|\n" +
	"\x14additionalParameters\x18\x03 \x03(\v2H.com.unified.grpc.oauth2.OAuth2AccessTokenResp.AdditionalParametersEntryR\x14additionalParameters\x12\x1b\n" +
	"\terror_msg\x18\x04 \x01(\tR\berrorMsg\x1aG\n" +
	"\x19AdditionalParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*6\n" +
	"\x11EncryptionKeyType\x12\a\n" +
	"\x03RSA\x10\x00\x12\x06\n" +
	"\x02EC\x10\x01\x12\a\n" +
	"\x03AES\x10\x02\x12\a\n" +
	"\x03SM2\x10\x032\xd1\x03\n" +
	"\tOAuth2Svc\x12[\n" +
	"\fgetSecretKey\x12%.com.unified.grpc.oauth2.SecretKeyReq\x1a\".com.unified.grpc.oauth2.SecretKey\"\x00\x12X\n" +
	"\vgetTokenKey\x12\x1e.com.unified.grpc.oauth2.Empty\x1a'.com.unified.grpc.oauth2.OAuth2TokenKey\"\x00\x12V\n" +
	"\x05login\x12%.com.unified.grpc.oauth2.LoginProfile\x1a$.com.unified.grpc.oauth2.OAuth2Token\"\x00\x12R\n" +
	"\x06logout\x12&.com.unified.grpc.oauth2.LogoutProfile\x1a\x1e.com.unified.grpc.oauth2.Empty\"\x00\x12a\n" +
	"\x05check\x12&.com.unified.grpc.oauth2.CheckTokenReq\x1a..com.unified.grpc.oauth2.OAuth2AccessTokenResp\"\x00BU\n" +
	"\x17com.unified.grpc.oauth2B\vOAuth2ProtoP\x01Z+github.com/lucky-xin/unified-oauth2-go/upmsb\x06proto3"

var (
	file_oauth2_proto_rawDescOnce sync.Once
	file_oauth2_proto_rawDescData []byte
)

func file_oauth2_proto_rawDescGZIP() []byte {
	file_oauth2_proto_rawDescOnce.Do(func() {
		file_oauth2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oauth2_proto_rawDesc), len(file_oauth2_proto_rawDesc)))
	})
	return file_oauth2_proto_rawDescData
}

var file_oauth2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_oauth2_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_oauth2_proto_goTypes = []any{
	(EncryptionKeyType)(0),        // 0: com.unified.grpc.oauth2.EncryptionKeyType
	(*Empty)(nil),                 // 1: com.unified.grpc.oauth2.Empty
	(*OAuth2TokenKey)(nil),        // 2: com.unified.grpc.oauth2.OAuth2TokenKey
	(*SecretKeyReq)(nil),          // 3: com.unified.grpc.oauth2.SecretKeyReq
	(*SecretKey)(nil),             // 4: com.unified.grpc.oauth2.SecretKey
	(*LoginProfile)(nil),          // 5: com.unified.grpc.oauth2.LoginProfile
	(*OAuth2Token)(nil),           // 6: com.unified.grpc.oauth2.OAuth2Token
	(*LogoutProfile)(nil),         // 7: com.unified.grpc.oauth2.LogoutProfile
	(*CheckTokenReq)(nil),         // 8: com.unified.grpc.oauth2.CheckTokenReq
	(*OAuth2AccessTokenResp)(nil), // 9: com.unified.grpc.oauth2.OAuth2AccessTokenResp
	nil,                           // 10: com.unified.grpc.oauth2.OAuth2Token.AdditionalInfoEntry
	nil,                           // 11: com.unified.grpc.oauth2.OAuth2AccessTokenResp.AdditionalParametersEntry
}
var file_oauth2_proto_depIdxs = []int32{
	0,  // 0: com.unified.grpc.oauth2.SecretKeyReq.type:type_name -> com.unified.grpc.oauth2.EncryptionKeyType
	0,  // 1: com.unified.grpc.oauth2.SecretKey.type:type_name -> com.unified.grpc.oauth2.EncryptionKeyType
	10, // 2: com.unified.grpc.oauth2.OAuth2Token.additionalInfo:type_name -> com.unified.grpc.oauth2.OAuth2Token.AdditionalInfoEntry
	6,  // 3: com.unified.grpc.oauth2.OAuth2AccessTokenResp.accessToken:type_name -> com.unified.grpc.oauth2.OAuth2Token
	11, // 4: com.unified.grpc.oauth2.OAuth2AccessTokenResp.additionalParameters:type_name -> com.unified.grpc.oauth2.OAuth2AccessTokenResp.AdditionalParametersEntry
	3,  // 5: com.unified.grpc.oauth2.OAuth2Svc.getSecretKey:input_type -> com.unified.grpc.oauth2.SecretKeyReq
	1,  // 6: com.unified.grpc.oauth2.OAuth2Svc.getTokenKey:input_type -> com.unified.grpc.oauth2.Empty
	5,  // 7: com.unified.grpc.oauth2.OAuth2Svc.login:input_type -> com.unified.grpc.oauth2.LoginProfile
	7,  // 8: com.unified.grpc.oauth2.OAuth2Svc.logout:input_type -> com.unified.grpc.oauth2.LogoutProfile
	8,  // 9: com.unified.grpc.oauth2.OAuth2Svc.check:input_type -> com.unified.grpc.oauth2.CheckTokenReq
	4,  // 10: com.unified.grpc.oauth2.OAuth2Svc.getSecretKey:output_type -> com.unified.grpc.oauth2.SecretKey
	2,  // 11: com.unified.grpc.oauth2.OAuth2Svc.getTokenKey:output_type -> com.unified.grpc.oauth2.OAuth2TokenKey
	6,  // 12: com.unified.grpc.oauth2.OAuth2Svc.login:output_type -> com.unified.grpc.oauth2.OAuth2Token
	1,  // 13: com.unified.grpc.oauth2.OAuth2Svc.logout:output_type -> com.unified.grpc.oauth2.Empty
	9,  // 14: com.unified.grpc.oauth2.OAuth2Svc.check:output_type -> com.unified.grpc.oauth2.OAuth2AccessTokenResp
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_oauth2_proto_init() }
func file_oauth2_proto_init() {
	if File_oauth2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oauth2_proto_rawDesc), len(file_oauth2_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oauth2_proto_goTypes,
		DependencyIndexes: file_oauth2_proto_depIdxs,
		EnumInfos:         file_oauth2_proto_enumTypes,
		MessageInfos:      file_oauth2_proto_msgTypes,
	}.Build()
	File_oauth2_proto = out.File
	file_oauth2_proto_goTypes = nil
	file_oauth2_proto_depIdxs = nil
}
