// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.0
// source: proto/oauth2.proto

package upms

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OAuth2Svc_GetTokenKey_FullMethodName = "/xyz.grpc.oauth2.OAuth2Svc/getTokenKey"
	OAuth2Svc_Login_FullMethodName       = "/xyz.grpc.oauth2.OAuth2Svc/login"
	OAuth2Svc_Logout_FullMethodName      = "/xyz.grpc.oauth2.OAuth2Svc/logout"
)

// OAuth2SvcClient is the client API for OAuth2Svc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 权限认证服务
type OAuth2SvcClient interface {
	// 获取token key
	GetTokenKey(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OAuth2TokenKey, error)
	// login
	Login(ctx context.Context, in *LoginProfile, opts ...grpc.CallOption) (*OAuth2Token, error)
	// logout
	Logout(ctx context.Context, in *LogoutProfile, opts ...grpc.CallOption) (*Empty, error)
}

type oAuth2SvcClient struct {
	cc grpc.ClientConnInterface
}

func NewOAuth2SvcClient(cc grpc.ClientConnInterface) OAuth2SvcClient {
	return &oAuth2SvcClient{cc}
}

func (c *oAuth2SvcClient) GetTokenKey(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OAuth2TokenKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OAuth2TokenKey)
	err := c.cc.Invoke(ctx, OAuth2Svc_GetTokenKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuth2SvcClient) Login(ctx context.Context, in *LoginProfile, opts ...grpc.CallOption) (*OAuth2Token, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OAuth2Token)
	err := c.cc.Invoke(ctx, OAuth2Svc_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuth2SvcClient) Logout(ctx context.Context, in *LogoutProfile, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, OAuth2Svc_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OAuth2SvcServer is the server API for OAuth2Svc service.
// All implementations must embed UnimplementedOAuth2SvcServer
// for forward compatibility.
//
// 权限认证服务
type OAuth2SvcServer interface {
	// 获取token key
	GetTokenKey(context.Context, *Empty) (*OAuth2TokenKey, error)
	// login
	Login(context.Context, *LoginProfile) (*OAuth2Token, error)
	// logout
	Logout(context.Context, *LogoutProfile) (*Empty, error)
	mustEmbedUnimplementedOAuth2SvcServer()
}

// UnimplementedOAuth2SvcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOAuth2SvcServer struct{}

func (UnimplementedOAuth2SvcServer) GetTokenKey(context.Context, *Empty) (*OAuth2TokenKey, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTokenKey not implemented")
}
func (UnimplementedOAuth2SvcServer) Login(context.Context, *LoginProfile) (*OAuth2Token, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedOAuth2SvcServer) Logout(context.Context, *LogoutProfile) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedOAuth2SvcServer) mustEmbedUnimplementedOAuth2SvcServer() {}
func (UnimplementedOAuth2SvcServer) testEmbeddedByValue()                   {}

// UnsafeOAuth2SvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OAuth2SvcServer will
// result in compilation errors.
type UnsafeOAuth2SvcServer interface {
	mustEmbedUnimplementedOAuth2SvcServer()
}

func RegisterOAuth2SvcServer(s grpc.ServiceRegistrar, srv OAuth2SvcServer) {
	// If the following call panics, it indicates UnimplementedOAuth2SvcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OAuth2Svc_ServiceDesc, srv)
}

func _OAuth2Svc_GetTokenKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuth2SvcServer).GetTokenKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuth2Svc_GetTokenKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuth2SvcServer).GetTokenKey(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuth2Svc_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuth2SvcServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuth2Svc_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuth2SvcServer).Login(ctx, req.(*LoginProfile))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuth2Svc_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuth2SvcServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuth2Svc_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuth2SvcServer).Logout(ctx, req.(*LogoutProfile))
	}
	return interceptor(ctx, in, info, handler)
}

// OAuth2Svc_ServiceDesc is the grpc.ServiceDesc for OAuth2Svc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OAuth2Svc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xyz.grpc.oauth2.OAuth2Svc",
	HandlerType: (*OAuth2SvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getTokenKey",
			Handler:    _OAuth2Svc_GetTokenKey_Handler,
		},
		{
			MethodName: "login",
			Handler:    _OAuth2Svc_Login_Handler,
		},
		{
			MethodName: "logout",
			Handler:    _OAuth2Svc_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/oauth2.proto",
}
