// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: proto/oauth2.proto

package upms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 空请求/响应
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_oauth2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oauth2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_oauth2_proto_rawDescGZIP(), []int{0}
}

// token key
type OAuth2TokenKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token key
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// 密钥id
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// 加密算法
	Alg           string `protobuf:"bytes,3,opt,name=alg,proto3" json:"alg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2TokenKey) Reset() {
	*x = OAuth2TokenKey{}
	mi := &file_proto_oauth2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2TokenKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2TokenKey) ProtoMessage() {}

func (x *OAuth2TokenKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oauth2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2TokenKey.ProtoReflect.Descriptor instead.
func (*OAuth2TokenKey) Descriptor() ([]byte, []int) {
	return file_proto_oauth2_proto_rawDescGZIP(), []int{1}
}

func (x *OAuth2TokenKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *OAuth2TokenKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OAuth2TokenKey) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

// 登录参数
type LoginProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 该字段为 客户端id
	ClientId string `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	// 该字段为 客户端密钥
	ClientSecret string `protobuf:"bytes,2,opt,name=clientSecret,proto3" json:"clientSecret,omitempty"`
	// 授权方式password,refresh_token,authorization_code,client_credentials。默认为password
	GrantType string `protobuf:"bytes,3,opt,name=grantType,proto3" json:"grantType,omitempty"`
	// The scope of the token. default read_write
	Scope string `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	// 登录用户名
	Username string `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	// 登录密码
	Password      string `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginProfile) Reset() {
	*x = LoginProfile{}
	mi := &file_proto_oauth2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginProfile) ProtoMessage() {}

func (x *LoginProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oauth2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginProfile.ProtoReflect.Descriptor instead.
func (*LoginProfile) Descriptor() ([]byte, []int) {
	return file_proto_oauth2_proto_rawDescGZIP(), []int{2}
}

func (x *LoginProfile) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LoginProfile) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *LoginProfile) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *LoginProfile) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *LoginProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginProfile) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 登录返回token
type OAuth2Token struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token value
	AccessToken string `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	// The token type, as introduced in draft 11 of the OAuth 2 spec.
	TokenType string `protobuf:"bytes,2,opt,name=tokenType,proto3" json:"tokenType,omitempty"`
	// The instant the token expires.
	IssuedAt int32 `protobuf:"varint,3,opt,name=issuedAt,proto3" json:"issuedAt,omitempty"`
	// Expires at
	ExpiresAt int32 `protobuf:"varint,5,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	// The refresh token associated with the access token, if any.
	RefreshToken string `protobuf:"bytes,6,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	// The scope of the token.
	Scope []string `protobuf:"bytes,7,rep,name=scope,proto3" json:"scope,omitempty"`
	// Additional information that token granters would like to add to the token, e.g. to support new token types.
	AdditionalInfo map[string]string `protobuf:"bytes,8,rep,name=additionalInfo,proto3" json:"additionalInfo,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OAuth2Token) Reset() {
	*x = OAuth2Token{}
	mi := &file_proto_oauth2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2Token) ProtoMessage() {}

func (x *OAuth2Token) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oauth2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2Token.ProtoReflect.Descriptor instead.
func (*OAuth2Token) Descriptor() ([]byte, []int) {
	return file_proto_oauth2_proto_rawDescGZIP(), []int{3}
}

func (x *OAuth2Token) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *OAuth2Token) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *OAuth2Token) GetIssuedAt() int32 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *OAuth2Token) GetExpiresAt() int32 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *OAuth2Token) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *OAuth2Token) GetScope() []string {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *OAuth2Token) GetAdditionalInfo() map[string]string {
	if x != nil {
		return x.AdditionalInfo
	}
	return nil
}

type LogoutProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutProfile) Reset() {
	*x = LogoutProfile{}
	mi := &file_proto_oauth2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutProfile) ProtoMessage() {}

func (x *LogoutProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oauth2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutProfile.ProtoReflect.Descriptor instead.
func (*LogoutProfile) Descriptor() ([]byte, []int) {
	return file_proto_oauth2_proto_rawDescGZIP(), []int{4}
}

func (x *LogoutProfile) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_proto_oauth2_proto protoreflect.FileDescriptor

const file_proto_oauth2_proto_rawDesc = "" +
	"\n" +
	"\x12proto/oauth2.proto\x12\x0fxyz.grpc.oauth2\"\a\n" +
	"\x05Empty\"D\n" +
	"\x0eOAuth2TokenKey\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x10\n" +
	"\x03alg\x18\x03 \x01(\tR\x03alg\"\xba\x01\n" +
	"\fLoginProfile\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12\"\n" +
	"\fclientSecret\x18\x02 \x01(\tR\fclientSecret\x12\x1c\n" +
	"\tgrantType\x18\x03 \x01(\tR\tgrantType\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\"\xde\x02\n" +
	"\vOAuth2Token\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x1c\n" +
	"\ttokenType\x18\x02 \x01(\tR\ttokenType\x12\x1a\n" +
	"\bissuedAt\x18\x03 \x01(\x05R\bissuedAt\x12\x1c\n" +
	"\texpiresAt\x18\x05 \x01(\x05R\texpiresAt\x12\"\n" +
	"\frefreshToken\x18\x06 \x01(\tR\frefreshToken\x12\x14\n" +
	"\x05scope\x18\a \x03(\tR\x05scope\x12X\n" +
	"\x0eadditionalInfo\x18\b \x03(\v20.xyz.grpc.oauth2.OAuth2Token.AdditionalInfoEntryR\x0eadditionalInfo\x1aA\n" +
	"\x13AdditionalInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"%\n" +
	"\rLogoutProfile\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xe1\x01\n" +
	"\tOAuth2Svc\x12H\n" +
	"\vgetTokenKey\x12\x16.xyz.grpc.oauth2.Empty\x1a\x1f.xyz.grpc.oauth2.OAuth2TokenKey\"\x00\x12F\n" +
	"\x05login\x12\x1d.xyz.grpc.oauth2.LoginProfile\x1a\x1c.xyz.grpc.oauth2.OAuth2Token\"\x00\x12B\n" +
	"\x06logout\x12\x1e.xyz.grpc.oauth2.LogoutProfile\x1a\x16.xyz.grpc.oauth2.Empty\"\x00BI\n" +
	"\x0fxyz.grpc.oauth2B\vOAuth2ProtoP\x01Z'github.com/lucky-xin/xyz-oauth2-go/upmsb\x06proto3"

var (
	file_proto_oauth2_proto_rawDescOnce sync.Once
	file_proto_oauth2_proto_rawDescData []byte
)

func file_proto_oauth2_proto_rawDescGZIP() []byte {
	file_proto_oauth2_proto_rawDescOnce.Do(func() {
		file_proto_oauth2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_oauth2_proto_rawDesc), len(file_proto_oauth2_proto_rawDesc)))
	})
	return file_proto_oauth2_proto_rawDescData
}

var file_proto_oauth2_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_oauth2_proto_goTypes = []any{
	(*Empty)(nil),          // 0: xyz.grpc.oauth2.Empty
	(*OAuth2TokenKey)(nil), // 1: xyz.grpc.oauth2.OAuth2TokenKey
	(*LoginProfile)(nil),   // 2: xyz.grpc.oauth2.LoginProfile
	(*OAuth2Token)(nil),    // 3: xyz.grpc.oauth2.OAuth2Token
	(*LogoutProfile)(nil),  // 4: xyz.grpc.oauth2.LogoutProfile
	nil,                    // 5: xyz.grpc.oauth2.OAuth2Token.AdditionalInfoEntry
}
var file_proto_oauth2_proto_depIdxs = []int32{
	5, // 0: xyz.grpc.oauth2.OAuth2Token.additionalInfo:type_name -> xyz.grpc.oauth2.OAuth2Token.AdditionalInfoEntry
	0, // 1: xyz.grpc.oauth2.OAuth2Svc.getTokenKey:input_type -> xyz.grpc.oauth2.Empty
	2, // 2: xyz.grpc.oauth2.OAuth2Svc.login:input_type -> xyz.grpc.oauth2.LoginProfile
	4, // 3: xyz.grpc.oauth2.OAuth2Svc.logout:input_type -> xyz.grpc.oauth2.LogoutProfile
	1, // 4: xyz.grpc.oauth2.OAuth2Svc.getTokenKey:output_type -> xyz.grpc.oauth2.OAuth2TokenKey
	3, // 5: xyz.grpc.oauth2.OAuth2Svc.login:output_type -> xyz.grpc.oauth2.OAuth2Token
	0, // 6: xyz.grpc.oauth2.OAuth2Svc.logout:output_type -> xyz.grpc.oauth2.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_oauth2_proto_init() }
func file_proto_oauth2_proto_init() {
	if File_proto_oauth2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_oauth2_proto_rawDesc), len(file_proto_oauth2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_oauth2_proto_goTypes,
		DependencyIndexes: file_proto_oauth2_proto_depIdxs,
		MessageInfos:      file_proto_oauth2_proto_msgTypes,
	}.Build()
	File_proto_oauth2_proto = out.File
	file_proto_oauth2_proto_goTypes = nil
	file_proto_oauth2_proto_depIdxs = nil
}
