// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.0
// source: proto/user_detail.proto

package upms

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserDetailsSvc_LoadDetailsByUserName_FullMethodName = "/xyz.grpc.upms.UserDetailsSvc/LoadDetailsByUserName"
	UserDetailsSvc_LoadSimpleByUserName_FullMethodName  = "/xyz.grpc.upms.UserDetailsSvc/LoadSimpleByUserName"
	UserDetailsSvc_LoadByUserId_FullMethodName          = "/xyz.grpc.upms.UserDetailsSvc/LoadByUserId"
	UserDetailsSvc_LoadUserBySocial_FullMethodName      = "/xyz.grpc.upms.UserDetailsSvc/LoadUserBySocial"
	UserDetailsSvc_TemporaryAccount_FullMethodName      = "/xyz.grpc.upms.UserDetailsSvc/TemporaryAccount"
)

// UserDetailsSvcClient is the client API for UserDetailsSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 用户详情查询服务
type UserDetailsSvcClient interface {
	// 根据用户名称获取详情信息
	LoadDetailsByUserName(ctx context.Context, in *LoadDetailsByUserNameReq, opts ...grpc.CallOption) (*OAuth2UserDetails, error)
	// 根据用户名称获取简单的信息（账号/密码/租户id。。。不包含权限）
	LoadSimpleByUserName(ctx context.Context, in *LoadDetailsByUserNameReq, opts ...grpc.CallOption) (*OAuth2UserDetails, error)
	// 根据用户id获取详情信息
	LoadByUserId(ctx context.Context, in *LoadByUserIdReq, opts ...grpc.CallOption) (*OAuth2UserDetails, error)
	// 根据社交登录code登录
	LoadUserBySocial(ctx context.Context, in *LoadUserBySocialReq, opts ...grpc.CallOption) (*OAuth2UserDetails, error)
	// 创建临时访问账号
	TemporaryAccount(ctx context.Context, in *TemporaryAccountReq, opts ...grpc.CallOption) (*OAuth2UserDetails, error)
}

type userDetailsSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewUserDetailsSvcClient(cc grpc.ClientConnInterface) UserDetailsSvcClient {
	return &userDetailsSvcClient{cc}
}

func (c *userDetailsSvcClient) LoadDetailsByUserName(ctx context.Context, in *LoadDetailsByUserNameReq, opts ...grpc.CallOption) (*OAuth2UserDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OAuth2UserDetails)
	err := c.cc.Invoke(ctx, UserDetailsSvc_LoadDetailsByUserName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDetailsSvcClient) LoadSimpleByUserName(ctx context.Context, in *LoadDetailsByUserNameReq, opts ...grpc.CallOption) (*OAuth2UserDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OAuth2UserDetails)
	err := c.cc.Invoke(ctx, UserDetailsSvc_LoadSimpleByUserName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDetailsSvcClient) LoadByUserId(ctx context.Context, in *LoadByUserIdReq, opts ...grpc.CallOption) (*OAuth2UserDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OAuth2UserDetails)
	err := c.cc.Invoke(ctx, UserDetailsSvc_LoadByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDetailsSvcClient) LoadUserBySocial(ctx context.Context, in *LoadUserBySocialReq, opts ...grpc.CallOption) (*OAuth2UserDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OAuth2UserDetails)
	err := c.cc.Invoke(ctx, UserDetailsSvc_LoadUserBySocial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDetailsSvcClient) TemporaryAccount(ctx context.Context, in *TemporaryAccountReq, opts ...grpc.CallOption) (*OAuth2UserDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OAuth2UserDetails)
	err := c.cc.Invoke(ctx, UserDetailsSvc_TemporaryAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserDetailsSvcServer is the server API for UserDetailsSvc service.
// All implementations must embed UnimplementedUserDetailsSvcServer
// for forward compatibility.
//
// 用户详情查询服务
type UserDetailsSvcServer interface {
	// 根据用户名称获取详情信息
	LoadDetailsByUserName(context.Context, *LoadDetailsByUserNameReq) (*OAuth2UserDetails, error)
	// 根据用户名称获取简单的信息（账号/密码/租户id。。。不包含权限）
	LoadSimpleByUserName(context.Context, *LoadDetailsByUserNameReq) (*OAuth2UserDetails, error)
	// 根据用户id获取详情信息
	LoadByUserId(context.Context, *LoadByUserIdReq) (*OAuth2UserDetails, error)
	// 根据社交登录code登录
	LoadUserBySocial(context.Context, *LoadUserBySocialReq) (*OAuth2UserDetails, error)
	// 创建临时访问账号
	TemporaryAccount(context.Context, *TemporaryAccountReq) (*OAuth2UserDetails, error)
	mustEmbedUnimplementedUserDetailsSvcServer()
}

// UnimplementedUserDetailsSvcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserDetailsSvcServer struct{}

func (UnimplementedUserDetailsSvcServer) LoadDetailsByUserName(context.Context, *LoadDetailsByUserNameReq) (*OAuth2UserDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadDetailsByUserName not implemented")
}
func (UnimplementedUserDetailsSvcServer) LoadSimpleByUserName(context.Context, *LoadDetailsByUserNameReq) (*OAuth2UserDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadSimpleByUserName not implemented")
}
func (UnimplementedUserDetailsSvcServer) LoadByUserId(context.Context, *LoadByUserIdReq) (*OAuth2UserDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadByUserId not implemented")
}
func (UnimplementedUserDetailsSvcServer) LoadUserBySocial(context.Context, *LoadUserBySocialReq) (*OAuth2UserDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadUserBySocial not implemented")
}
func (UnimplementedUserDetailsSvcServer) TemporaryAccount(context.Context, *TemporaryAccountReq) (*OAuth2UserDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method TemporaryAccount not implemented")
}
func (UnimplementedUserDetailsSvcServer) mustEmbedUnimplementedUserDetailsSvcServer() {}
func (UnimplementedUserDetailsSvcServer) testEmbeddedByValue()                        {}

// UnsafeUserDetailsSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserDetailsSvcServer will
// result in compilation errors.
type UnsafeUserDetailsSvcServer interface {
	mustEmbedUnimplementedUserDetailsSvcServer()
}

func RegisterUserDetailsSvcServer(s grpc.ServiceRegistrar, srv UserDetailsSvcServer) {
	// If the following call panics, it indicates UnimplementedUserDetailsSvcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserDetailsSvc_ServiceDesc, srv)
}

func _UserDetailsSvc_LoadDetailsByUserName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadDetailsByUserNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDetailsSvcServer).LoadDetailsByUserName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDetailsSvc_LoadDetailsByUserName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDetailsSvcServer).LoadDetailsByUserName(ctx, req.(*LoadDetailsByUserNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDetailsSvc_LoadSimpleByUserName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadDetailsByUserNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDetailsSvcServer).LoadSimpleByUserName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDetailsSvc_LoadSimpleByUserName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDetailsSvcServer).LoadSimpleByUserName(ctx, req.(*LoadDetailsByUserNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDetailsSvc_LoadByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadByUserIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDetailsSvcServer).LoadByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDetailsSvc_LoadByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDetailsSvcServer).LoadByUserId(ctx, req.(*LoadByUserIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDetailsSvc_LoadUserBySocial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadUserBySocialReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDetailsSvcServer).LoadUserBySocial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDetailsSvc_LoadUserBySocial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDetailsSvcServer).LoadUserBySocial(ctx, req.(*LoadUserBySocialReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDetailsSvc_TemporaryAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemporaryAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDetailsSvcServer).TemporaryAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDetailsSvc_TemporaryAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDetailsSvcServer).TemporaryAccount(ctx, req.(*TemporaryAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserDetailsSvc_ServiceDesc is the grpc.ServiceDesc for UserDetailsSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserDetailsSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xyz.grpc.upms.UserDetailsSvc",
	HandlerType: (*UserDetailsSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadDetailsByUserName",
			Handler:    _UserDetailsSvc_LoadDetailsByUserName_Handler,
		},
		{
			MethodName: "LoadSimpleByUserName",
			Handler:    _UserDetailsSvc_LoadSimpleByUserName_Handler,
		},
		{
			MethodName: "LoadByUserId",
			Handler:    _UserDetailsSvc_LoadByUserId_Handler,
		},
		{
			MethodName: "LoadUserBySocial",
			Handler:    _UserDetailsSvc_LoadUserBySocial_Handler,
		},
		{
			MethodName: "TemporaryAccount",
			Handler:    _UserDetailsSvc_TemporaryAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user_detail.proto",
}
