// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: proto/user_detail.proto

package upms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取用户详情请求
type LoadDetailsByUserNameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadDetailsByUserNameReq) Reset() {
	*x = LoadDetailsByUserNameReq{}
	mi := &file_proto_user_detail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadDetailsByUserNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadDetailsByUserNameReq) ProtoMessage() {}

func (x *LoadDetailsByUserNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_detail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadDetailsByUserNameReq.ProtoReflect.Descriptor instead.
func (*LoadDetailsByUserNameReq) Descriptor() ([]byte, []int) {
	return file_proto_user_detail_proto_rawDescGZIP(), []int{0}
}

func (x *LoadDetailsByUserNameReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

// 根据用户ID获取详情请求
type LoadByUserIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadByUserIdReq) Reset() {
	*x = LoadByUserIdReq{}
	mi := &file_proto_user_detail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadByUserIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadByUserIdReq) ProtoMessage() {}

func (x *LoadByUserIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_detail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadByUserIdReq.ProtoReflect.Descriptor instead.
func (*LoadByUserIdReq) Descriptor() ([]byte, []int) {
	return file_proto_user_detail_proto_rawDescGZIP(), []int{1}
}

func (x *LoadByUserIdReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 社交登录请求
type LoadUserBySocialReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 登录类型
	LoginType string `protobuf:"bytes,1,opt,name=login_type,json=loginType,proto3" json:"login_type,omitempty"`
	// 社交账号
	Account       string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadUserBySocialReq) Reset() {
	*x = LoadUserBySocialReq{}
	mi := &file_proto_user_detail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadUserBySocialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadUserBySocialReq) ProtoMessage() {}

func (x *LoadUserBySocialReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_detail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadUserBySocialReq.ProtoReflect.Descriptor instead.
func (*LoadUserBySocialReq) Descriptor() ([]byte, []int) {
	return file_proto_user_detail_proto_rawDescGZIP(), []int{2}
}

func (x *LoadUserBySocialReq) GetLoginType() string {
	if x != nil {
		return x.LoginType
	}
	return ""
}

func (x *LoadUserBySocialReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

// 创建临时访问账号请求
type TemporaryAccountReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 账号
	Principal string `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	// 登录类型
	LoginType     string `protobuf:"bytes,2,opt,name=login_type,json=loginType,proto3" json:"login_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemporaryAccountReq) Reset() {
	*x = TemporaryAccountReq{}
	mi := &file_proto_user_detail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporaryAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporaryAccountReq) ProtoMessage() {}

func (x *TemporaryAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_detail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporaryAccountReq.ProtoReflect.Descriptor instead.
func (*TemporaryAccountReq) Descriptor() ([]byte, []int) {
	return file_proto_user_detail_proto_rawDescGZIP(), []int{3}
}

func (x *TemporaryAccountReq) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *TemporaryAccountReq) GetLoginType() string {
	if x != nil {
		return x.LoginType
	}
	return ""
}

// 用户详情
type OAuth2UserDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 部门ID
	DeptId int64 `protobuf:"varint,2,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	// 租户ID
	TenantId int64 `protobuf:"varint,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// 用户账号
	Username string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	// 用户密码
	Password string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	// 用户别名
	Nickname string `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 是否为简化对象
	Simple bool `protobuf:"varint,7,opt,name=simple,proto3" json:"simple,omitempty"`
	// 是否启用
	Enabled bool `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// 账号是否未过期
	AccountNonExpired bool `protobuf:"varint,9,opt,name=account_non_expired,json=accountNonExpired,proto3" json:"account_non_expired,omitempty"`
	// 凭据是否未过期
	CredentialsNonExpired bool `protobuf:"varint,10,opt,name=credentials_non_expired,json=credentialsNonExpired,proto3" json:"credentials_non_expired,omitempty"`
	// 账号是否未锁定
	AccountNonLocked bool `protobuf:"varint,11,opt,name=account_non_locked,json=accountNonLocked,proto3" json:"account_non_locked,omitempty"`
	// 角色ID列表
	RoleIds []int64 `protobuf:"varint,12,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	// 角色类型列表
	RoleTypes []int32 `protobuf:"varint,13,rep,packed,name=role_types,json=roleTypes,proto3" json:"role_types,omitempty"`
	// 数据权限ID列表
	DataScopeIds []int64 `protobuf:"varint,14,rep,packed,name=data_scope_ids,json=dataScopeIds,proto3" json:"data_scope_ids,omitempty"`
	// 权限列表
	Authorities []*OAuth2GrantedAuthority `protobuf:"bytes,15,rep,name=authorities,proto3" json:"authorities,omitempty"`
	// 错误信息
	ErrorMsg      string `protobuf:"bytes,16,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2UserDetails) Reset() {
	*x = OAuth2UserDetails{}
	mi := &file_proto_user_detail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2UserDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2UserDetails) ProtoMessage() {}

func (x *OAuth2UserDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_detail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2UserDetails.ProtoReflect.Descriptor instead.
func (*OAuth2UserDetails) Descriptor() ([]byte, []int) {
	return file_proto_user_detail_proto_rawDescGZIP(), []int{4}
}

func (x *OAuth2UserDetails) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OAuth2UserDetails) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

func (x *OAuth2UserDetails) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *OAuth2UserDetails) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OAuth2UserDetails) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *OAuth2UserDetails) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *OAuth2UserDetails) GetSimple() bool {
	if x != nil {
		return x.Simple
	}
	return false
}

func (x *OAuth2UserDetails) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *OAuth2UserDetails) GetAccountNonExpired() bool {
	if x != nil {
		return x.AccountNonExpired
	}
	return false
}

func (x *OAuth2UserDetails) GetCredentialsNonExpired() bool {
	if x != nil {
		return x.CredentialsNonExpired
	}
	return false
}

func (x *OAuth2UserDetails) GetAccountNonLocked() bool {
	if x != nil {
		return x.AccountNonLocked
	}
	return false
}

func (x *OAuth2UserDetails) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *OAuth2UserDetails) GetRoleTypes() []int32 {
	if x != nil {
		return x.RoleTypes
	}
	return nil
}

func (x *OAuth2UserDetails) GetDataScopeIds() []int64 {
	if x != nil {
		return x.DataScopeIds
	}
	return nil
}

func (x *OAuth2UserDetails) GetAuthorities() []*OAuth2GrantedAuthority {
	if x != nil {
		return x.Authorities
	}
	return nil
}

func (x *OAuth2UserDetails) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 授权权限
type OAuth2GrantedAuthority struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 权限字符串
	Permission string `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	// 访问次数
	Authorities   int64 `protobuf:"varint,2,opt,name=authorities,proto3" json:"authorities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2GrantedAuthority) Reset() {
	*x = OAuth2GrantedAuthority{}
	mi := &file_proto_user_detail_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2GrantedAuthority) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2GrantedAuthority) ProtoMessage() {}

func (x *OAuth2GrantedAuthority) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_detail_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2GrantedAuthority.ProtoReflect.Descriptor instead.
func (*OAuth2GrantedAuthority) Descriptor() ([]byte, []int) {
	return file_proto_user_detail_proto_rawDescGZIP(), []int{5}
}

func (x *OAuth2GrantedAuthority) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *OAuth2GrantedAuthority) GetAuthorities() int64 {
	if x != nil {
		return x.Authorities
	}
	return 0
}

var File_proto_user_detail_proto protoreflect.FileDescriptor

const file_proto_user_detail_proto_rawDesc = "" +
	"\n" +
	"\x17proto/user_detail.proto\x12\rxyz.grpc.upms\"7\n" +
	"\x18LoadDetailsByUserNameReq\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\"*\n" +
	"\x0fLoadByUserIdReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"N\n" +
	"\x13LoadUserBySocialReq\x12\x1d\n" +
	"\n" +
	"login_type\x18\x01 \x01(\tR\tloginType\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\"R\n" +
	"\x13TemporaryAccountReq\x12\x1c\n" +
	"\tprincipal\x18\x01 \x01(\tR\tprincipal\x12\x1d\n" +
	"\n" +
	"login_type\x18\x02 \x01(\tR\tloginType\"\xbb\x04\n" +
	"\x11OAuth2UserDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\adept_id\x18\x02 \x01(\x03R\x06deptId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\x03R\btenantId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x06 \x01(\tR\bnickname\x12\x16\n" +
	"\x06simple\x18\a \x01(\bR\x06simple\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\x12.\n" +
	"\x13account_non_expired\x18\t \x01(\bR\x11accountNonExpired\x126\n" +
	"\x17credentials_non_expired\x18\n" +
	" \x01(\bR\x15credentialsNonExpired\x12,\n" +
	"\x12account_non_locked\x18\v \x01(\bR\x10accountNonLocked\x12\x19\n" +
	"\brole_ids\x18\f \x03(\x03R\aroleIds\x12\x1d\n" +
	"\n" +
	"role_types\x18\r \x03(\x05R\troleTypes\x12$\n" +
	"\x0edata_scope_ids\x18\x0e \x03(\x03R\fdataScopeIds\x12G\n" +
	"\vauthorities\x18\x0f \x03(\v2%.xyz.grpc.upms.OAuth2GrantedAuthorityR\vauthorities\x12\x1b\n" +
	"\terror_msg\x18\x10 \x01(\tR\berrorMsg\"Z\n" +
	"\x16OAuth2GrantedAuthority\x12\x1e\n" +
	"\n" +
	"permission\x18\x01 \x01(\tR\n" +
	"permission\x12 \n" +
	"\vauthorities\x18\x02 \x01(\x03R\vauthorities2\xdd\x03\n" +
	"\x0eUserDetailsSvc\x12b\n" +
	"\x15LoadDetailsByUserName\x12'.xyz.grpc.upms.LoadDetailsByUserNameReq\x1a .xyz.grpc.upms.OAuth2UserDetails\x12a\n" +
	"\x14LoadSimpleByUserName\x12'.xyz.grpc.upms.LoadDetailsByUserNameReq\x1a .xyz.grpc.upms.OAuth2UserDetails\x12P\n" +
	"\fLoadByUserId\x12\x1e.xyz.grpc.upms.LoadByUserIdReq\x1a .xyz.grpc.upms.OAuth2UserDetails\x12X\n" +
	"\x10LoadUserBySocial\x12\".xyz.grpc.upms.LoadUserBySocialReq\x1a .xyz.grpc.upms.OAuth2UserDetails\x12X\n" +
	"\x10TemporaryAccount\x12\".xyz.grpc.upms.TemporaryAccountReq\x1a .xyz.grpc.upms.OAuth2UserDetailsBT\n" +
	"\x15xyz.grpc.user.detailsB\x10UserDetailsProtoP\x01Z'github.com/lucky-xin/xyz-oauth2-go/upmsb\x06proto3"

var (
	file_proto_user_detail_proto_rawDescOnce sync.Once
	file_proto_user_detail_proto_rawDescData []byte
)

func file_proto_user_detail_proto_rawDescGZIP() []byte {
	file_proto_user_detail_proto_rawDescOnce.Do(func() {
		file_proto_user_detail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_detail_proto_rawDesc), len(file_proto_user_detail_proto_rawDesc)))
	})
	return file_proto_user_detail_proto_rawDescData
}

var file_proto_user_detail_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_user_detail_proto_goTypes = []any{
	(*LoadDetailsByUserNameReq)(nil), // 0: xyz.grpc.upms.LoadDetailsByUserNameReq
	(*LoadByUserIdReq)(nil),          // 1: xyz.grpc.upms.LoadByUserIdReq
	(*LoadUserBySocialReq)(nil),      // 2: xyz.grpc.upms.LoadUserBySocialReq
	(*TemporaryAccountReq)(nil),      // 3: xyz.grpc.upms.TemporaryAccountReq
	(*OAuth2UserDetails)(nil),        // 4: xyz.grpc.upms.OAuth2UserDetails
	(*OAuth2GrantedAuthority)(nil),   // 5: xyz.grpc.upms.OAuth2GrantedAuthority
}
var file_proto_user_detail_proto_depIdxs = []int32{
	5, // 0: xyz.grpc.upms.OAuth2UserDetails.authorities:type_name -> xyz.grpc.upms.OAuth2GrantedAuthority
	0, // 1: xyz.grpc.upms.UserDetailsSvc.LoadDetailsByUserName:input_type -> xyz.grpc.upms.LoadDetailsByUserNameReq
	0, // 2: xyz.grpc.upms.UserDetailsSvc.LoadSimpleByUserName:input_type -> xyz.grpc.upms.LoadDetailsByUserNameReq
	1, // 3: xyz.grpc.upms.UserDetailsSvc.LoadByUserId:input_type -> xyz.grpc.upms.LoadByUserIdReq
	2, // 4: xyz.grpc.upms.UserDetailsSvc.LoadUserBySocial:input_type -> xyz.grpc.upms.LoadUserBySocialReq
	3, // 5: xyz.grpc.upms.UserDetailsSvc.TemporaryAccount:input_type -> xyz.grpc.upms.TemporaryAccountReq
	4, // 6: xyz.grpc.upms.UserDetailsSvc.LoadDetailsByUserName:output_type -> xyz.grpc.upms.OAuth2UserDetails
	4, // 7: xyz.grpc.upms.UserDetailsSvc.LoadSimpleByUserName:output_type -> xyz.grpc.upms.OAuth2UserDetails
	4, // 8: xyz.grpc.upms.UserDetailsSvc.LoadByUserId:output_type -> xyz.grpc.upms.OAuth2UserDetails
	4, // 9: xyz.grpc.upms.UserDetailsSvc.LoadUserBySocial:output_type -> xyz.grpc.upms.OAuth2UserDetails
	4, // 10: xyz.grpc.upms.UserDetailsSvc.TemporaryAccount:output_type -> xyz.grpc.upms.OAuth2UserDetails
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_user_detail_proto_init() }
func file_proto_user_detail_proto_init() {
	if File_proto_user_detail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_detail_proto_rawDesc), len(file_proto_user_detail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_detail_proto_goTypes,
		DependencyIndexes: file_proto_user_detail_proto_depIdxs,
		MessageInfos:      file_proto_user_detail_proto_msgTypes,
	}.Build()
	File_proto_user_detail_proto = out.File
	file_proto_user_detail_proto_goTypes = nil
	file_proto_user_detail_proto_depIdxs = nil
}
